language: node_js
sudo: required
before_install:
 - docker login -u "$DOCKER_USERNAME" -P "$DOCKER_PASSWORD"
install: true
before_script:
- export DOCKER_HOST="$DOCKER_HOST"
script: 
- docker build -t $DOCKER_USERNAME/htmltest .
- docker push $DOCKER_USERNAME/htmltest
after_success:
- docker stop htmltest
- docker rm htmltest
- docker run -p 8088:80 -d --name htmltest $DOCKER_USERNAME/htmltest:latest
service: docker
env:
  global:
    